-- MySQL Script generated by MySQL Workbench
-- Пн 22 окт 2018 08:36:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema galleryDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema galleryDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `galleryDB` ;
USE `galleryDB` ;

-- -----------------------------------------------------
-- Table `galleryDB`.`cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `galleryDB`.`cards` ;

CREATE TABLE IF NOT EXISTS `galleryDB`.`cards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `img` TEXT(50) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `views` VARCHAR(100) NULL,
  `rating` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
