-- MySQL Script generated by MySQL Workbench
-- Ср 24 окт 2018 13:34:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema img_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema img_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `img_db` ;
USE `img_db` ;

-- -----------------------------------------------------
-- Table `img_db`.`img`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `img_db`.`img` ;

CREATE TABLE IF NOT EXISTS `img_db`.`img` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `src` TEXT(300) NOT NULL,
  `size` INT(4) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `views` INT(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
